= G13 Apps
Fusetim <fusetim@gmx.com>
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

[abstract]
Simple little applications for your G13 keyboard. Very useful for https://github.com/ecraven/g13[g13] users.

IMPORTANT: Work In Progress -- Applications are slowly developed step by step.

toc::[]

== How does it work?

The G13 mini-applications will use the keys already used for this purpose in Windows :

- Thus the L1-4 keys will be used to interact with the launched application. 
- The BD button will be used to return to the menu.

[NOTE]
--
However we will not change the configuration of the https://github.com/ecraven/g13[G13 driver] automatically. The configuration will have to be changed manually with the one supplied. 

See the keybind link:g13-apps.bind[].
--

Applications will be similar to the original G13. You will find a list of applications implemented or to be implemented.

== What applications?

- [x] Menu -- the application selector
- [x] Clock -- analog and digital
- [ ] Music Player -- based upon MPRIS data

[NOTE]
--
All applications can be disabled at compile time. +
*Now works with enum_dispatch v0.3.2!*
--

NOTE: Feel free to open an issue (or PR) to request another application.

== Getting started

First of all, you will need a recent Rust setup. See https://rustup.rs[Rustup] installation guide, if needed.

To build g13-apps, you need to clone the repo:
```shell
$ git clone https://github.com/fusetim/g13-apps.git
```

Before compiling g13-apps, you will need to know the paths to the in and out pipes of the https://github.com/ecraven/g13[G13 driver].
By default, it's `/tmp/g13-0` (in) and `/tmp/g13-0_out` (out).

.Set-up the env-var
```shell
$ set -x G13_IN /run/g13d/g13-0
$ set -x G13_OUT /run/g13d/g13-0_out
```

[WARNING]
Please note that the indicated pipe paths are included and compiled. + 
If the paths ever change, it will be necessary to recompile the whole app.

And finally, you can build the apps with all the features you want:
```shell
$ cargo build --release [--features <feature1> [feature2..] ]
```

.Build G13-apps with clock feature:
====
If you want the clock app, for example, just add the clock feature, like this:
```shell
$ cargo build --release --features clock
```
====

And now, enjoy your new application at `./target/release/g13-apps`.

All you have to do now is configure the right key-binding (in the G13 driver's config) and you will be able to take advantage of all the applications you have chosen. See link:g13-apps.bind[] for example.

NOTE: Implementation as a user service is planned in the future.

NOTE: If wanted, you can install g13-apps as a system app with `cargo install`.

== License

© 2020 - FuseTim +
All rights reserved

Program offered under license CeCILL v2.1footnote:[Free license under French law compatible with the GNU GPL licenses. See section link:license.txt#L289[5.3.2].] +
https://cecill.info/licences/Licence_CeCILL_V2.1-fr.html[License in French] | https://cecill.info/licences/Licence_CeCILL_V2.1-en.html[License in English]