name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      env: 
        G13_IN: "/somewhere"
        G13_OUT: "/somewhere"
    - name: Run tests
      run: cargo test --verbose
      env: 
        G13_IN: "/somewhere"
        G13_OUT: "/somewhere"